Added metric prefix macros
cfengine/libntech pull request #123
Opened 2021-03-19 12:48 UTC by larsewi

I see extensively in the source code that sizes are calculated like this `5 * 1024 * 1024`. I believe it would be more readable if we used metric prefix macros like `MEBIBYTE(5)`.

2021-03-19 13:14 UTC, larsewi commented
I should probably add unit tests I guess.

2021-03-20 16:27 UTC, olehermanse commented on libutils/definitions.h
> +#define TEBIBYTE(n) n * 1024 * 1024 * 1024 * 1024
I would put them in parenthesis, although it probably doesn't matter in most cases.

```suggestion
#define KIBIBYTE(n) (n * 1024)
#define MEBIBYTE(n) (n * 1024 * 1024)
#define GIBIBYTE(n) (n * 1024 * 1024 * 1024)
#define TEBIBYTE(n) (n * 1024 * 1024 * 1024 * 1024)
```

2021-03-23 12:48 UTC, olehermanse commented on tests/unit/definitions_test.c
> +    assert_int_equal(TEBIBYTE(19), 20890720000000);
Adding some random numbers is fine, but I would test the basic 0, 1, and 2 for each of them, for example:

```
    assert_int_equal(GIBIBYTE(0), 0);
    assert_int_equal(GIBIBYTE(1), 1024 * MEBIBYTE(1));
    assert_int_equal(2 * GIBIBYTE(1), GIBIBYTE(2));
    assert_int_equal(GIBIBYTE(6), 6442451000);
    assert_int_equal(GIBIBYTE(10), 10737420000);
    assert_int_equal(GIBIBYTE(18), 19327350000);
```

2021-03-23 12:49 UTC, olehermanse requested changes
LGTM, but there seems to be some problem with your last commit. Please make sure you are committing with an e-mail address that you have added to your GitHub account.

2021-03-23 12:51 UTC, olehermanse requested changes
Some more things need fixing.

2021-03-23 12:51 UTC, olehermanse commented on tests/unit/definitions_test.c
> +        unit_test(test_metric_prefixes())
```suggestion
        unit_test(test_metric_prefixes)
```

Give it the function pointer, don't call the function.

2021-03-23 12:51 UTC, olehermanse commented on libutils/definitions.h
> +#define TEBIBYTE(n) (n * 1024 * 1024 * 1024 * 1024)
```suggestion
#define KIBIBYTE(n) (n * 1024L)
#define MEBIBYTE(n) (n * 1024L * 1024L)
#define GIBIBYTE(n) (n * 1024L * 1024L * 1024L)
#define TEBIBYTE(n) (n * 1024L * 1024L * 1024L * 1024L)
```

I guess you have to write it like this to avoide overflow.

2021-03-24 08:44 UTC, vpodzime approved these changes
Looks good to me.

2021-03-24 19:23 UTC, olehermanse requested changes
Please fix the commit so that GH recognizes who wrote this.

I guess you have to fix your git config, then do `git commit --amend --reset-author`.

2021-03-25 09:12 UTC, vpodzime approved these changes
ACK

2021-03-26 14:10 UTC, olehermanse approved these changes

2021-03-26 14:10 UTC, merged