Change license of libntech from GPLv3 to Apache License
cfengine/libntech pull request #188
Opened 2023-08-11 11:27 UTC by vpodzime

To make libntech usable in non-GPL projects and better suited for wider usage.

Committed without authorship to avoid affecting statistics, these are not line of code changes.

2023-08-11 11:29 UTC, cf-bottom requested changes
Please use a company e-mail instead of v***@mykolab.com

2023-08-11 11:29 UTC, vpodzime commented
This leaves the following occurrences of GPL in the repo:
```
$ git grep '\(General Public License\|GPL\)'
LICENSE:the GNU General Public License (GPL) v.3.0 or other applicable
libutils/man.c:        ".\\\"under the terms of the GNU General Public License as published by the\n"
libutils/man.c:        ".\\\"GNU General Public License for more details.\n"
libutils/man.c:        ".\\\"You should have received a copy of the GNU General Public License\n"
```
where the former one is the mention of GPL in the COSL license (which we are not changing so the mention has to stay there) and the latter is the code that prints a copyright notice for man pages which is currently only used in CFEngine which is GPL licensed and so the license there is correct. Ideally, the code should be able to use a different license, but that's out of scope here.

2023-08-16 05:34 UTC, kacf approved these changes
A couple of things I spotted:

* The commercial license at the bottom of `LICENSE` still mentions GPL as the alternative.

* `libutils/man.c` still has GPL in its copyright C string.

Everything else looks good to me!

2023-08-16 07:13 UTC, vpodzime commented
> A couple of things I spotted:

Yes, I mentioned both [above](https://github.com/cfengine/libntech/pull/188#issuecomment-1674598691)

2023-08-16 07:43 UTC, kacf commented
Ah right, right, I scrolled past that too quickly. All good then.

2023-08-16 14:45 UTC, olehermanse approved these changes

2023-08-16 14:46 UTC, merged